# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fc1PFe3qqNSuoTyhtNx58xtPFjPbQakL
"""

import streamlit as st
import os
import urllib.request
import numpy as np
import cv2
from PIL import Image
from tensorflow.keras.models import load_model

MODEL_URL = "https://github.com/Fachrurraji80/deteksi-daun-mangga/releases/download/v1.0/model.keras"
MODEL_PATH = "model.keras"

if not os.path.exists(MODEL_PATH):
    with st.spinner("Mengunduh model CNN..."):
        urllib.request.urlretrieve(MODEL_URL, MODEL_PATH)

# =========================
# KONFIGURASI
# =========================
IMG_SIZE = 224

# ⚠️ HARUS 8 KELAS & URUTANNYA SESUAI train_gen.class_indices
CLASS_NAMES = [
    "Anthracnose",
    "Bacterial Canker",
    "Cutting Weevil",
    "Die Back",
    "Gall Midge",
    "Healthy",
    "Powdery Mildew",
    "Sooty Mould"
]

# =========================
# LOAD MODEL
# =========================
@st.cache_resource
def load_cnn_model():
    return load_model(MODEL_PATH)

model = load_cnn_model()

# =========================
# PREPROCESSING (SAMA DENGAN TRAINING)
# =========================
def preprocess_image(image):
    image = cv2.resize(image, (IMG_SIZE, IMG_SIZE))
    image = image.astype("float32") / 255.0
    image = np.expand_dims(image, axis=0)
    return image

# =========================
# STREAMLIT UI
# =========================
st.set_page_config(
    page_title="Deteksi Penyakit Daun Mangga",
    layout="centered"
)

st.title("🌿 Deteksi Penyakit Daun Mangga")
st.write(
    "Aplikasi ini menggunakan **Convolutional Neural Network (CNN – EfficientNetB0)** "
    "untuk mendeteksi penyakit pada daun mangga."
)

uploaded_file = st.file_uploader(
    "📤 Upload gambar daun mangga",
    type=["jpg", "jpeg", "png"]
)

if uploaded_file is not None:
    image = Image.open(uploaded_file).convert("RGB")
    image_np = np.array(image)

    st.subheader("📷 Citra Asli")
    st.image(image, use_container_width=True)

    if st.button("🔍 Deteksi Penyakit"):
        processed_image = preprocess_image(image_np)

        st.write("Input shape:", processed_image.shape)

        prediction = model.predict(processed_image)

        st.write("Raw model prediction:", prediction)

        class_index = np.argmax(prediction)
        confidence = prediction[0][class_index]

        st.subheader("✅ Hasil Deteksi")
        st.success(f"**Penyakit:** {CLASS_NAMES[class_index]}")
        st.info(f"**Tingkat Kepercayaan:** {confidence * 100:.2f}%")

        # 🔎 tampilkan semua probabilitas (opsional tapi DISARANKAN)
        st.subheader("📊 Probabilitas Semua Kelas")
        for i, prob in enumerate(prediction[0]):
            st.write(f"{CLASS_NAMES[i]}: {prob*100:.2f}%")



